# Helyz's hyprland.conf

$mainMod = SUPER
$terminal = kitty
$fileManager = thunar
$menu = hyprlauncher

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, X, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Second Monitor (BenQ) on the Left
monitor = HDMI-A-1, 1920x1080@60, 0x0, 1
# Main Screen on the Right
monitor = eDP-2, 2560x1600@120, 1920x0, 1
